# Generated by Django 5.1.7 on 2025-05-01 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0003_course_jenjang_kelas'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChainNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('duration_per_participant', models.DurationField()),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Ongoing'), (2, 'Finished')], default=0)),
                ('course_session', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='courses.coursesession')),
            ],
        ),
    ]
