# Generated by Django 5.1.7 on 2025-05-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChainNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('duration_per_participant', models.DurationField()),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Ongoing'), (2, 'Finished')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ChainNoteTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('is_skipped', models.BooleanField(default=False)),
            ],
        ),
    ]
