# Generated by Django 5.1.7 on 2025-05-06 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain_notes', '0001_initial'),
        ('courses', '0003_course_jenjang_kelas'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChainNoteTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('is_skipped', models.BooleanField(default=False)),
                ('chain_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chain_notes.chainnote')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courseparticipant')),
            ],
        ),
    ]
