# Generated by Django 5.1.7 on 2025-05-15 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chain_notes', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chainnote',
            name='course_session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='courses.coursesession'),
        ),
        migrations.AddField(
            model_name='chainnoteturn',
            name='chain_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chain_notes.chainnote'),
        ),
        migrations.AddField(
            model_name='chainnoteturn',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courseparticipant'),
        ),
    ]
