# Generated by Django 5.1.7 on 2025-06-10 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain_notes', '0002_initial'),
        ('courses', '0004_alter_participantpoint_course_participant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chainnote',
            name='course_session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses.coursesession'),
        ),
        migrations.AlterField(
            model_name='chainnoteturn',
            name='chain_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='chain_notes.chainnote'),
        ),
    ]
