# Generated by Django 5.1.7 on 2025-05-18 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0003_participantpoint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_study_case', models.ImageField(blank=True, null=True, upload_to='study-case-image/')),
                ('total_point', models.FloatField(default=100)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('time_range', models.DurationField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Draft', 'DRAF'), ('Active', 'ACTIVE'), ('Finished', 'FINISHED')], default='Draft', max_length=50)),
                ('course_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.coursesession')),
            ],
        ),
        migrations.CreateModel(
            name='StudyCaseQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=255, null=True)),
                ('study_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studycases.studycase')),
            ],
        ),
        migrations.CreateModel(
            name='StudyCaseAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('point', models.FloatField(default=0)),
                ('is_submitted', models.BooleanField(default=False)),
                ('is_evaluated', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('study_case_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studycases.studycasequestion')),
            ],
        ),
    ]
