# Generated by Django 5.1.7 on 2025-05-22 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_participantpoint'),
        ('studycases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studycase',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draf'), ('Active', 'Active'), ('Finished', 'Finished')], default='Draft', max_length=50),
        ),
        migrations.AlterField(
            model_name='studycaseanswer',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courseparticipant'),
        ),
        migrations.AlterField(
            model_name='studycasequestion',
            name='study_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='studycases.studycase'),
        ),
    ]
