# Generated by Django 5.2 on 2025-04-29 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studycases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studycase',
            name='title',
        ),
        migrations.AddField(
            model_name='studycase',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studycaseanswer',
            name='is_evaluated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studycase',
            name='question',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
