# Generated by Django 5.2 on 2025-04-29 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studycases', '0002_remove_studycase_title_studycase_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studycase',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studycase',
            name='time_range',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
