# Generated by Django 5.1.7 on 2025-05-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studycases', '0002_studycaseattempt_is_evaluated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studycase',
            name='time_range',
            field=models.DurationField(default='00:00:30'),
            preserve_default=False,
        ),
    ]
