# Generated by Django 5.2 on 2025-04-29 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studycases', '0003_alter_studycase_started_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studycase',
            name='question',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
