# Generated by Django 5.1.7 on 2025-05-25 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studycases', '0003_alter_studycase_time_range'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studycase',
            old_name='total_point',
            new_name='max_point_per_question',
        ),
    ]
