# Generated by Django 5.1.7 on 2025-05-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studycases', '0004_rename_total_point_studycase_max_point_per_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studycasequestion',
            name='question',
            field=models.CharField(default='-', max_length=255),
            preserve_default=False,
        ),
    ]
