# Generated by Django 5.2 on 2025-04-29 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studycases', '0004_alter_studycase_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studycase',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='studycaseanswer',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studycaseanswer',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
