# Generated by Django 5.1.7 on 2025-06-13 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studycases', '0005_alter_studycasequestion_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studycasequestion',
            name='question',
            field=models.TextField(),
        ),
    ]
