# Generated by Django 5.2 on 2025-04-30 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studycases', '0005_remove_studycase_created_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studycase',
            old_name='question',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='studycaseanswer',
            name='study_case',
        ),
        migrations.CreateModel(
            name='StudyCaseQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=255, null=True)),
                ('study_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studycases.studycase')),
            ],
        ),
        migrations.AddField(
            model_name='studycaseanswer',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='studycases.studycasequestion'),
            preserve_default=False,
        ),
    ]
