# Generated by Django 5.2 on 2025-04-30 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studycases', '0006_rename_question_studycase_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studycase',
            old_name='total_points',
            new_name='total_point',
        ),
        migrations.RenameField(
            model_name='studycaseanswer',
            old_name='question',
            new_name='study_case_question',
        ),
    ]
