# Generated by Django 5.2 on 2025-05-01 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studycases', '0007_rename_total_points_studycase_total_point_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studycaseanswer',
            old_name='score',
            new_name='point',
        ),
    ]
