# Generated by Django 5.1.7 on 2025-05-18 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_achieved', models.FloatField(default=0)),
                ('course_participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courseparticipant')),
            ],
        ),
    ]
