# Generated by Django 5.1.7 on 2025-03-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='jenjang_kelas',
            field=models.CharField(choices=[('SMA Kelas 1', 'SMA_KELAS_1'), ('SMA Kelas 2', 'SMA_KELAS_2'), ('SMA Kelas 3', 'SMA_KELAS_3')], default='SMA Kelas 1', max_length=50),
        ),
    ]
