# Generated by Django 5.2 on 2025-04-30 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_jenjang_kelas'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_point', models.FloatField(default=0)),
                ('point_achieved', models.FloatField(default=0)),
                ('course_participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courseparticipant')),
            ],
        ),
    ]
