# Generated by Django 5.1.7 on 2025-05-12 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_jenjang_kelas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinstructor',
            name='course_participant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses.courseparticipant'),
        ),
    ]
