# Generated by Django 5.2 on 2025-05-01 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_participantpoint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participantpoint',
            name='total_point',
        ),
    ]
