# Generated by Django 5.2 on 2025-05-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nama_lengkap',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
