# Generated by Django 5.1.7 on 2025-05-22 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0003_participantpoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='resource-file/')),
                ('course_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.coursesession')),
            ],
        ),
    ]
