# Generated by Django 5.2 on 2025-05-08 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0005_remove_participantpoint_total_point'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='resource-file/')),
                ('resource_type', models.CharField(choices=[('Link', 'LINK'), ('File', 'FILE')], default='File', max_length=50)),
                ('course_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.coursesession')),
            ],
        ),
    ]
