# Generated by Django 5.1.7 on 2025-05-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_profile', models.ImageField(blank=True, null=True, upload_to='teacher-profile/')),
                ('dateOfBirth', models.DateField(blank=True, null=True)),
                ('school', models.CharField(blank=True, max_length=255, null=True)),
                ('student_class', models.CharField(choices=[('SMA Kelas 1', 'SMA_KELAS_1'), ('SMA Kelas 2', 'SMA_KELAS_2'), ('SMA Kelas 3', 'SMA_KELAS_3')], default='SMA Kelas 1', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_profile', models.ImageField(blank=True, null=True, upload_to='teacher-profile/')),
                ('dateOfBirth', models.DateField(blank=True, null=True)),
                ('school', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
