# Generated by Django 5.1.7 on 2025-05-29 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_studentprofile_user_alter_teacherprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='image_profile',
            field=models.ImageField(blank=True, null=True, upload_to='student-profile/'),
        ),
    ]
