# Generated by Django 5.1.7 on 2025-05-23 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Finished', 'Finished')], default='Draft', max_length=10),
        ),
    ]
