# Generated by Django 5.1.7 on 2025-04-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
