# Generated by Django 5.1.7 on 2025-05-24 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_participantpoint'),
        ('quiz', '0002_alter_quiz_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='course_session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='courses.coursesession'),
        ),
    ]
